# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    desc "Build aplication"
    lane :build do
      gradle(task: "clean assembleDebug")
    end

    desc "Perform Unit tests"
    lane :tests do
      gradle(task: "test")
    end

    desc "Perform Instrumented tests"
    lane :ui_tests do
      gradle(
        task: 'clean'
      )
      gradle(
        task: 'assemble',
        build_type: 'Debug'
      )
      gradle(
        task: 'assemble',
        build_type: 'AndroidTest'
      )
      screengrab
    end

end